server:
  port: 8882
eureka:
#  instance:
#    hostname: clientName
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  application:
    name: order-client
PRODUCT-CLIENT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
evn:
  dev111
label:
  release
